FROM concourse/concourse-ci
# https://github.com/concourse/concourse/blob/master/ci/dockerfiles/concourse-ci/Dockerfile

#RUN apt-get update && apt-get install zip unzip curl wget bzr -y

#ADD https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 /usr/bin/jq
#RUN chmod 775 /usr/bin/jq

RUN gem install therubyracer bookbindery vienna rack-rewrite sendgrid-ruby --no-rdoc --no-ri
