---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-docs-pipeline}

inputs:
  - name: docs-ci
  - name: docs

outputs:
  - name: docs-app

params:
  app_name:
  routes:

run:
  path: docs-ci/ci/tasks/build-docs-app.sh
